// <auto-generated />
using System;
using ChurchApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChurchApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229020205_guestdetail")]
    partial class guestdetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ChurchApp.Models.AccountabilityCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurrenceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelatedTaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToWorkerId");

                    b.HasIndex("CreatedByWorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("AccountabilityCases");
                });

            modelBuilder.Entity("ChurchApp.Models.AccountabilityMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisibleToLevels")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("SenderWorkerId");

                    b.ToTable("AccountabilityMessages");
                });

            modelBuilder.Entity("ChurchApp.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<int>("Children")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Men")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedByWorkerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Teenagers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Women")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AttendanceDate");

                    b.HasIndex("RecordedByWorkerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceName");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("ChurchApp.Models.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangedByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ChangedByWorkerId");

                    b.HasIndex("TableName", "RecordId");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("ChurchApp.Models.BreakRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApprovedByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentHandler")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingAssignments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RelieveOfficerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResubmissionRequestDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByWorkerId");

                    b.HasIndex("RelieveOfficerId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("WorkerId");

                    b.ToTable("BreakRequests");
                });

            modelBuilder.Entity("ChurchApp.Models.BreakRequestHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("BreakRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionByWorkerId");

                    b.HasIndex("BreakRequestId");

                    b.ToTable("BreakRequestHistories");
                });

            modelBuilder.Entity("ChurchApp.Models.CaseAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformedByWorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("PerformedByWorkerId");

                    b.ToTable("CaseActions");
                });

            modelBuilder.Entity("ChurchApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssistantHeadWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectorateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssistantHeadWorkerId");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("HeadWorkerId");

                    b.HasIndex("Name", "DirectorateId")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ChurchApp.Models.Directorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssistantHeadWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeadWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssistantHeadWorkerId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HeadWorkerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Directorates");
                });

            modelBuilder.Entity("ChurchApp.Models.ExcuseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApprovedByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CustomServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("CustomServiceTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalActionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NominatedBackupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResubmissionRequestDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByWorkerId");

                    b.HasIndex("NominatedBackupId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("WorkerId");

                    b.ToTable("ExcuseRequests");
                });

            modelBuilder.Entity("ChurchApp.Models.ExcuseRequestHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExcuseRequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActionByWorkerId");

                    b.HasIndex("ExcuseRequestId");

                    b.ToTable("ExcuseRequestHistories");
                });

            modelBuilder.Entity("ChurchApp.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthMonth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CurrentPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HowFoundUs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsBaptisedByWater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRCCGMember")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecondTimer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherChurch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedByWorkerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SecondVisitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondVisitRecordedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondVisitRecordedByWorkerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VisitingDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("WantsToBecomeMember")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("WantsToJoinWorkforce")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasFilter("[Email] IS NOT NULL AND [Email] != ''");

                    b.HasIndex("GuestNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .HasFilter("[PhoneNumber] IS NOT NULL AND [PhoneNumber] != ''");

                    b.HasIndex("RecordedByWorkerId");

                    b.HasIndex("RecordingDate");

                    b.HasIndex("ServiceId");

                    b.HasIndex("VisitingDate");

                    b.HasIndex("IsSecondTimer", "IsActive");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("ChurchApp.Models.OfferingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminComments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByWorkerId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OfferingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OfferingTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfferingTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedByWorkerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByWorkerId");

                    b.HasIndex("OfferingTypeId");

                    b.HasIndex("RecordedByWorkerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OfferingRecords");
                });

            modelBuilder.Entity("ChurchApp.Models.OfferingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("OfferingTypes");
                });

            modelBuilder.Entity("ChurchApp.Models.ProfileUpdateRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApproverWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedChanges")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByWorkerId");

                    b.HasIndex("ApproverWorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("ProfileUpdateRequests");
                });

            modelBuilder.Entity("ChurchApp.Models.RecordNomination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("NominatorWorkerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomineeWorkerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "ServiceDate", "NomineeWorkerId", "RecordType")
                        .IsUnique();

                    b.ToTable("RecordNominations");
                });

            modelBuilder.Entity("ChurchApp.Models.RejectionNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileUpdateRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RejectedByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RejectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileUpdateRequestId");

                    b.HasIndex("RejectedByWorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("RejectionNotifications");
                });

            modelBuilder.Entity("ChurchApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ChurchApp.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrencePattern")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SpecificDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("SpecificEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("SpecificStartTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WeekOfMonth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ChurchApp.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeaderWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LeaderWorkerId");

                    b.HasIndex("Name", "DepartmentId")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ChurchApp.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BelieverBaptismCertificatePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BibleCollegeCertificatePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanAccessAdminPanel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanApproveProfiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageWorkers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanViewReports")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompliancePercentage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateJoinedChurch")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DirectorateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBelieverBaptism")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBibleCollege")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSOD")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWorkerInTraining")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastOrdinationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrdinationLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrdinationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportPhotoPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousChurch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousChurchRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousChurchUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProfileSubmitted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SODCertificatePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Stage1Approved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Stage2Approved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WeddingAnniversary")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerInTrainingCertificatePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WorkerId")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ChurchApp.Models.WorkerHierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DirectorateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReportsToWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("ReportsToWorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerHierarchies");
                });

            modelBuilder.Entity("ChurchApp.Models.AccountabilityCase", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "AssignedToWorker")
                        .WithMany()
                        .HasForeignKey("AssignedToWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "CreatedByWorker")
                        .WithMany()
                        .HasForeignKey("CreatedByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToWorker");

                    b.Navigation("CreatedByWorker");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ChurchApp.Models.AccountabilityMessage", b =>
                {
                    b.HasOne("ChurchApp.Models.AccountabilityCase", "Case")
                        .WithMany("Messages")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.AccountabilityMessage", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId");

                    b.HasOne("ChurchApp.Models.Worker", "SenderWorker")
                        .WithMany()
                        .HasForeignKey("SenderWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("SenderWorker");
                });

            modelBuilder.Entity("ChurchApp.Models.AttendanceRecord", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedByWorkerId")
                        .HasPrincipalKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecordedBy");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ChurchApp.Models.AuditTrail", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "ChangedByWorker")
                        .WithMany()
                        .HasForeignKey("ChangedByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByWorker");
                });

            modelBuilder.Entity("ChurchApp.Models.BreakRequest", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "ApprovedByWorker")
                        .WithMany()
                        .HasForeignKey("ApprovedByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "RelieveOfficer")
                        .WithMany()
                        .HasForeignKey("RelieveOfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Worker", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByWorker");

                    b.Navigation("RelieveOfficer");

                    b.Navigation("Supervisor");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ChurchApp.Models.BreakRequestHistory", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "ActionByWorker")
                        .WithMany()
                        .HasForeignKey("ActionByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.BreakRequest", "BreakRequest")
                        .WithMany("History")
                        .HasForeignKey("BreakRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionByWorker");

                    b.Navigation("BreakRequest");
                });

            modelBuilder.Entity("ChurchApp.Models.CaseAction", b =>
                {
                    b.HasOne("ChurchApp.Models.AccountabilityCase", "Case")
                        .WithMany("Actions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Worker", "PerformedByWorker")
                        .WithMany()
                        .HasForeignKey("PerformedByWorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("PerformedByWorker");
                });

            modelBuilder.Entity("ChurchApp.Models.Department", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "AssistantHeadWorker")
                        .WithMany()
                        .HasForeignKey("AssistantHeadWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Directorate", "Directorate")
                        .WithMany("Departments")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Worker", "HeadWorker")
                        .WithMany()
                        .HasForeignKey("HeadWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssistantHeadWorker");

                    b.Navigation("Directorate");

                    b.Navigation("HeadWorker");
                });

            modelBuilder.Entity("ChurchApp.Models.Directorate", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "AssistantHeadWorker")
                        .WithMany()
                        .HasForeignKey("AssistantHeadWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "HeadWorker")
                        .WithMany()
                        .HasForeignKey("HeadWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssistantHeadWorker");

                    b.Navigation("HeadWorker");
                });

            modelBuilder.Entity("ChurchApp.Models.ExcuseRequest", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "ApprovedByWorker")
                        .WithMany()
                        .HasForeignKey("ApprovedByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "NominatedBackup")
                        .WithMany()
                        .HasForeignKey("NominatedBackupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Service", "Service")
                        .WithMany("ExcuseRequests")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByWorker");

                    b.Navigation("NominatedBackup");

                    b.Navigation("Service");

                    b.Navigation("Supervisor");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ChurchApp.Models.ExcuseRequestHistory", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "ActionByWorker")
                        .WithMany()
                        .HasForeignKey("ActionByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.ExcuseRequest", "ExcuseRequest")
                        .WithMany("History")
                        .HasForeignKey("ExcuseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionByWorker");

                    b.Navigation("ExcuseRequest");
                });

            modelBuilder.Entity("ChurchApp.Models.Guest", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", null)
                        .WithMany()
                        .HasForeignKey("RecordedByWorkerId")
                        .HasPrincipalKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ChurchApp.Models.OfferingRecord", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByWorkerId")
                        .HasPrincipalKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.OfferingType", "OfferingType")
                        .WithMany("OfferingRecords")
                        .HasForeignKey("OfferingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Worker", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedByWorkerId")
                        .HasPrincipalKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("OfferingType");

                    b.Navigation("RecordedBy");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ChurchApp.Models.OfferingType", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasPrincipalKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ChurchApp.Models.ProfileUpdateRequest", b =>
                {
                    b.HasOne("ChurchApp.Models.Worker", "ApprovedByWorker")
                        .WithMany()
                        .HasForeignKey("ApprovedByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "ApproverWorker")
                        .WithMany()
                        .HasForeignKey("ApproverWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByWorker");

                    b.Navigation("ApproverWorker");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ChurchApp.Models.RecordNomination", b =>
                {
                    b.HasOne("ChurchApp.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ChurchApp.Models.RejectionNotification", b =>
                {
                    b.HasOne("ChurchApp.Models.ProfileUpdateRequest", "ProfileUpdateRequest")
                        .WithMany()
                        .HasForeignKey("ProfileUpdateRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Worker", "RejectedByWorker")
                        .WithMany()
                        .HasForeignKey("RejectedByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfileUpdateRequest");

                    b.Navigation("RejectedByWorker");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ChurchApp.Models.Unit", b =>
                {
                    b.HasOne("ChurchApp.Models.Department", "Department")
                        .WithMany("Units")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChurchApp.Models.Worker", "LeaderWorker")
                        .WithMany()
                        .HasForeignKey("LeaderWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("LeaderWorker");
                });

            modelBuilder.Entity("ChurchApp.Models.Worker", b =>
                {
                    b.HasOne("ChurchApp.Models.Department", "Department")
                        .WithMany("Workers")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ChurchApp.Models.Directorate", "Directorate")
                        .WithMany("Workers")
                        .HasForeignKey("DirectorateId");

                    b.HasOne("ChurchApp.Models.Worker", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Unit", "Unit")
                        .WithMany("Workers")
                        .HasForeignKey("UnitId");

                    b.Navigation("Department");

                    b.Navigation("Directorate");

                    b.Navigation("Supervisor");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ChurchApp.Models.WorkerHierarchy", b =>
                {
                    b.HasOne("ChurchApp.Models.Directorate", "Directorate")
                        .WithMany()
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "ReportsToWorker")
                        .WithMany()
                        .HasForeignKey("ReportsToWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChurchApp.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directorate");

                    b.Navigation("ReportsToWorker");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ChurchApp.Models.AccountabilityCase", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ChurchApp.Models.BreakRequest", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("ChurchApp.Models.Department", b =>
                {
                    b.Navigation("Units");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ChurchApp.Models.Directorate", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ChurchApp.Models.ExcuseRequest", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("ChurchApp.Models.OfferingType", b =>
                {
                    b.Navigation("OfferingRecords");
                });

            modelBuilder.Entity("ChurchApp.Models.Service", b =>
                {
                    b.Navigation("ExcuseRequests");
                });

            modelBuilder.Entity("ChurchApp.Models.Unit", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ChurchApp.Models.Worker", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
